import { Department, Doctor, Hospital, Ambulance, UpazilaHealthData } from './types';

export const CD_PATH_NAME = 'CD Path & Hospital Pvt. Ltd.';

export const HOSPITALS: Hospital[] = [
  {
    id: 'h1',
    name: 'Cumilla Medical College & Hospital (COMCH)',
    facilityType: 'মেডিকেল কলেজ হাসপাতাল',
    categoryType: 'সরকারি',
    area: 'টমসন ব্রিজ',
    address: 'House #29, Kotbari Road, Tomsom Bridge, Cumilla',
    phone: '081-77563',
    bedCapacity: '500+',
    hasICU: true,
    hasCCU: true,
    hasNICU: true,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.CARDIOLOGY, Department.SURGERY, Department.GYNAECOLOGY, Department.PEDIATRICS, Department.ORTHOPEDICS, Department.NEUROLOGY, Department.NEUROSURGERY, Department.GASTROENTEROLOGY, Department.NEPHROLOGY, Department.ONCOLOGY, Department.ENT, Department.DERMATOLOGY, Department.PSYCHIATRY, Department.EYE, Department.DENTAL, Department.UROLOGY],
    services: ['Emergency 24/7', 'ICU', 'NICU', 'CCU', 'PICU', 'HDU', 'Dialysis', 'CT Scan', 'MRI', 'Pathology Lab', 'Blood Bank'],
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h2',
    name: 'CD Path & Hospital Pvt. Ltd.',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'বাদুড়তলা',
    address: 'Shishu Monagal Road, Badurtala, Cumilla-3500',
    phone: '081-68082, 01716-277211',
    bedCapacity: '50',
    hasICU: true,
    hasCCU: true,
    hasNICU: true,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.ONCOLOGY, Department.CARDIOLOGY, Department.MEDICINE, Department.GASTROENTEROLOGY, Department.GYNAECOLOGY, Department.ENT, Department.ORTHOPEDICS, Department.NEUROLOGY, Department.NEPHROLOGY, Department.PEDIATRICS, Department.DERMATOLOGY, Department.ENDOCRINOLOGY, Department.UROLOGY],
    services: ['ক্যান্সার ও রেডিওথেরাপি', 'কার্ডিওলজি', 'নিউরোলজি', 'ডায়ালাইসিস', 'আইসিইউ', 'সিসিইউ', 'এনআইসিইউ', 'সিটি স্ক্যান', 'এমআরআই', 'অ্যাম্বুলেন্স'],
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h3',
    name: 'Cumilla Medical Center Pvt. Ltd. (Tower Hospital)',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'কান্দিরপাড়',
    address: 'Comilla Tower, Laksam Road, Kandirpar, Cumilla',
    phone: '081-68921, 01966-777888',
    bedCapacity: '50',
    hasICU: true,
    hasCCU: true,
    hasNICU: true,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.CARDIOLOGY, Department.GYNAECOLOGY, Department.SURGERY, Department.MEDICINE, Department.ORTHOPEDICS, Department.ENT, Department.CHEST_MEDICINE, Department.VASCULAR_SURGERY, Department.PHYSICAL_MEDICINE],
    services: ['২২+ বিভাগ', 'কার্ডিওলজি', 'ল্যাপারোস্কোপিক সার্জারি', 'ভাস্কুলার সার্জারি', 'ইনফার্টিলিটি', 'আইসিইউ', 'সিসিইউ', 'ডায়ালাইসিস'],
    image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h4',
    name: 'Moon Hospital Ltd.',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'ঝাউতলা',
    address: 'Shahid Khawaja Nizamuddin Road, Jhautola, Cumilla',
    phone: '01766-556655, 081-68161',
    bedCapacity: '30',
    hasICU: true,
    hasCCU: true,
    hasNICU: true,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.CARDIOLOGY, Department.PEDIATRICS, Department.MEDICINE, Department.GYNAECOLOGY, Department.ORTHOPEDICS, Department.UROLOGY],
    services: ['২১+ স্পেশালিস্ট বিভাগ', 'শিশু ও নবজাতক কেয়ার', 'কার্ডিও কেয়ার', 'আইসিইউ', 'অপারেশন থিয়েটার'],
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h5',
    name: 'General Hospital, Cumilla',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'রেইসকোর্স / শাসনগাছা',
    address: 'Shasongacha, Railgate, Cumilla',
    phone: '081-76930',
    bedCapacity: '35',
    hasICU: true,
    hasCCU: true,
    hasNICU: true,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.GYNAECOLOGY, Department.ORTHOPEDICS, Department.ENT, Department.DERMATOLOGY, Department.DENTAL, Department.EYE],
    services: ['সাধারণ ও ল্যাপারোস্কোপিক সার্জারি', 'চর্ম ও যৌন', 'আইসিইউ', 'অর্থোপেডিক ও ট্রমা'],
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h6',
    name: 'Mukti Hospital',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'রেইসকোর্স',
    address: 'Race Course, Sasongacha, Cumilla',
    phone: '01711-796905',
    bedCapacity: '20',
    hasICU: true,
    hasCCU: true,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.GYNAECOLOGY, Department.ORTHOPEDICS],
    services: ['জেনারেল মেডিসিন', 'সার্জারি', 'গাইনি ও প্রসূতি', 'এক্স-রে ও প্যাথলজি'],
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h7',
    name: 'Midland Hospital Pvt. Ltd.',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'কান্দিরপাড়',
    address: 'Ram Ghatla, Laksam Road, Kandirpar, Cumilla',
    phone: '01711-795740',
    bedCapacity: '35',
    hasICU: true,
    hasCCU: true,
    hasNICU: true,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.KIDNEY_SPECIALIST, Department.CARDIOLOGY],
    services: ['ICU', 'CCU', 'OT', 'ডায়ালাইসিস', 'X-ray', 'Pathology'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h8',
    name: 'Cumilla City Hospital Pvt. Ltd.',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'বাদুড়তলা',
    address: 'Badurtala, Cumilla',
    phone: '01819-607156',
    bedCapacity: '20',
    hasICU: true,
    hasCCU: true,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.GYNAECOLOGY],
    services: ['ICU', 'CCU', 'OT', 'X-ray', 'Pathology'],
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h9',
    name: 'Cumilla Hospital & Diagnostic',
    facilityType: 'প্রাইভেট হাসপাতাল ও ডায়াগনস্টিক',
    categoryType: 'বেসরকারি',
    area: 'ঝাউতলা',
    address: 'Dharmasagar West, Jhautola, Cumilla',
    phone: '01711-422510',
    bedCapacity: '20',
    hasICU: true,
    hasCCU: true,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.GASTROENTEROLOGY, Department.PEDIATRICS],
    services: ['ICU', 'CCU', 'OT', 'X-ray', 'Pathology', 'Diagnostic'],
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h10',
    name: 'Gomati Hospital Pvt. Ltd.',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'কান্দিরপাড়',
    address: 'Nazrul Avenue, Kandirpar, Cumilla',
    phone: '01711-798083',
    bedCapacity: '20',
    hasICU: true,
    hasCCU: true,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.CARDIOLOGY, Department.SURGERY],
    services: ['ICU', 'CCU', 'OT', 'X-ray', 'Pathology'],
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h11',
    name: 'Cumilla Trauma Center',
    facilityType: 'বিশেষায়িত ট্রমা ও অর্থোপেডিক',
    categoryType: 'বেসরকারি',
    area: 'কান্দিরপাড়',
    address: '511, Nazrul Avenue, Ranir Bazar Road, Kandirpar, Cumilla',
    phone: '01735-274020, 01855-666777',
    bedCapacity: '20',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.ORTHOPEDICS, Department.ENT, Department.SURGERY],
    services: ['অর্থোপেডিকস', 'ট্রমা ও জয়েন্ট রিপ্লেসমেন্ট', 'আইসিইউ', 'জরুরি ওটি', 'ডিজিটাল এক্স-রে'],
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h12',
    name: 'Popular Hospital Pvt. Ltd.',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'কান্দিরপাড়',
    address: 'Laksam Road, Ramghat, Kandirpar, Cumilla',
    phone: '01711-785442',
    bedCapacity: '10',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: false,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.GYNAECOLOGY],
    services: ['জেনারেল সার্ভিস', 'এক্স-রে', 'প্যাথলজি'],
    image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h13',
    name: 'Cumilla Diabetic Hospital',
    facilityType: 'বিশেষায়িত ডায়াবেটিক হাসপাতাল',
    categoryType: 'আধা-সরকারি',
    area: 'বাগিচাগাঁও',
    address: 'Sulivan Road, Bagichagaon, Cumilla',
    phone: '081-65145',
    bedCapacity: '30',
    hasICU: true,
    hasCCU: true,
    hasNICU: false,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: false,
    specialties: [Department.ENDOCRINOLOGY, Department.MEDICINE, Department.NEPHROLOGY, Department.EYE],
    services: ['ডায়াবেটিস ও হরমোন চিকিৎসা', 'ডায়াবেটিক ফুট কেয়ার', 'প্যাথলজি', 'ডায়ালাইসিস'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h14',
    name: 'Cumilla Mission Hospital',
    facilityType: 'মিশন হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'শাসনগাছা',
    address: 'Shasongacha, Railgate, Cumilla',
    phone: '01739-142170',
    bedCapacity: '20',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: false,
    hasMRI: false,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.GYNAECOLOGY],
    services: ['জেনারেল মেডিসিন', 'সার্জারি', 'গাইনি'],
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h15',
    name: 'Neuron Hospital & Diagnostic Center',
    facilityType: 'নিউরোলজি ও বিশেষায়িত হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'রেইসকোর্স',
    address: 'Race Course, Cumilla',
    phone: '01717-323305, 01999-901234',
    bedCapacity: '10',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.NEUROLOGY, Department.NEURO_CRITICAL_CARE, Department.MEDICINE],
    services: ['নিউরোলজি', 'ক্রিটিক্যাল কেয়ার', 'ইইজি', 'ইএমজি', 'ডায়াগনস্টিক'],
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h16',
    name: 'United Hospital, Cumilla',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'টমসন ব্রিজ',
    address: 'Tomsom Bridge, Cumilla',
    phone: '01712-243281, 01711-555444',
    bedCapacity: '20',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.SURGERY, Department.COLORECTAL_SURGERY, Department.MEDICINE],
    services: ['লেজার ও কোলোরেক্টাল সার্জারি', 'জেনারেল মেডিসিন', 'অপারেশন থিয়েটার'],
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h17',
    name: 'Eye Hospital & Training Center',
    facilityType: 'চক্ষু হাসপাতাল ও প্রশিক্ষণ কেন্দ্র',
    categoryType: 'সরকারি',
    area: 'আলেকারচর',
    address: 'Shankarpur, Alekharchar, Cumilla',
    phone: '081-64500',
    bedCapacity: '100',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: false,
    specialties: [Department.EYE],
    services: ['চক্ষু সার্জারি (মাইক্রো-সার্জারি)', 'ফ্যাকো সার্জারি', 'কর্নিয়া ও রেটিনা কেয়ার', 'প্রশিক্ষণ'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    confidence: 'MEDIUM'
  },
  {
    id: 'h18',
    name: 'Maynamati Cantonment General Hospital',
    facilityType: 'ক্যান্টনমেন্ট জেনারেল হাসপাতাল',
    categoryType: 'সামরিক',
    area: 'ক্যান্টনমেন্ট',
    address: 'Tipra Bazar, Cantonment, Cumilla',
    phone: '01769-332734',
    bedCapacity: '10',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: false,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.GYNAECOLOGY],
    services: ['জেনারেল চিকিৎসা', 'জরুরি ওটি', 'ল্যাবরেটরি'],
    image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h19',
    name: 'Mamata Mother & Child Hospital',
    facilityType: 'মা ও শিশু হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'রানীর বাজার',
    address: 'Talpukur (S), Ranir Bazar Road, Cumilla',
    phone: '01711-116538',
    bedCapacity: '10',
    hasICU: true,
    hasCCU: false,
    hasNICU: true,
    hasDialysis: false,
    hasCTScan: false,
    hasMRI: false,
    specialties: [Department.PEDIATRICS, Department.GYNAECOLOGY],
    services: ['শিশু বিশেষজ্ঞ', 'প্রসূতি ও সিজারিয়ান ওটি', 'এনআইসিইউ'],
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h20',
    name: 'Cumilla Central Hospital Pvt. Ltd.',
    facilityType: 'প্রাইভেট হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'টমসন ব্রিজ',
    address: 'Syed Mansion, Tomsom Bridge, Cumilla',
    phone: '01711-068091',
    bedCapacity: '30',
    hasICU: true,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: false,
    specialties: [Department.MEDICINE, Department.SURGERY, Department.GYNAECOLOGY],
    services: ['আইসিইউ', 'জরুরি বিভাগ', 'অপারেশন থিয়েটার'],
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h21',
    name: 'Cumilla Maternity Clinic',
    facilityType: 'ম্যাটারনিটি ক্লিনিক',
    categoryType: 'বেসরকারি',
    area: 'ঠাকুরপাড়া',
    address: '699, Rammala Road, Thakurpara, Cumilla',
    phone: '01711-186406',
    bedCapacity: '10',
    hasICU: false,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    specialties: [Department.GYNAECOLOGY],
    services: ['নরমাল ডেলিভারি', 'সিজারিয়ান অপারেশন', 'মাতৃস্বাস্থ্য পরামর্শ'],
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'h22',
    name: 'Cumilla Dental General Hospital',
    facilityType: 'ডেন্টাল হাসপাতাল',
    categoryType: 'বেসরকারি',
    area: 'রেইসকোর্স',
    address: 'Race Course, Cumilla',
    phone: '01711-262884',
    bedCapacity: '10',
    hasICU: false,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    specialties: [Department.DENTAL],
    services: ['রুট ক্যানেল', 'দাঁত তোলা ও স্কেলিং', 'অর্থোডন্টিক ব্রেসেস', 'ডেন্টাল এক্স-রে'],
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  // Major Diagnostic Centres
  {
    id: 'd1_center',
    name: 'Popular Diagnostic Center Ltd., Cumilla',
    facilityType: 'ডায়াগনস্টিক ও কনসালটেশন সেন্টার',
    categoryType: 'বেসরকারি',
    area: 'কান্দিরপাড়',
    address: 'House #57, Laksam Road, Ramghat, Kandirpar, Cumilla',
    phone: '09666-787825',
    bedCapacity: 'ডে কেয়ার',
    hasICU: false,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.CARDIOLOGY, Department.NEUROLOGY, Department.GYNAECOLOGY, Department.PEDIATRICS, Department.PHYSICAL_MEDICINE, Department.DERMATOLOGY, Department.ENDOCRINOLOGY, Department.HEPATOLOGY],
    services: ['1.5T MRI', '128 Slice CT Scan', '4D Ultrasound', 'Digital X-ray', 'Automated Lab', 'Specialist Chambers'],
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'd2_center',
    name: 'Labaid Ltd. (Diagnostic), Cumilla',
    facilityType: 'ডায়াগনস্টিক সেন্টার',
    categoryType: 'বেসরকারি',
    area: 'টমসন ব্রিজ / কান্দিরপাড়',
    address: 'House-622/3, 2nd Kandirpar, Laksam Road, Cumilla',
    phone: '10606, 01766-662288',
    bedCapacity: 'ল্যাব',
    hasICU: false,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.CARDIOLOGY, Department.GASTROENTEROLOGY, Department.MEDICINE],
    services: ['CT Scan', 'MRI', 'ইসিজি ও ইকোকার্ডিওগ্রাফি', 'হরমোন টেস্ট', 'ডিজিটাল প্যাথলজি'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'd3_center',
    name: 'Ibn Sina Diagnostic & Consultation Center',
    facilityType: 'ডায়াগনস্টিক ও কনসালটেশন সেন্টার',
    categoryType: 'বেসরকারি',
    area: 'টমসন ব্রিজ',
    address: 'House #29, Kotbari Road, Tomsom Bridge, Cumilla',
    phone: '01844-142500',
    bedCapacity: 'ল্যাব',
    hasICU: false,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.MEDICINE, Department.ORTHOPEDICS, Department.ENT, Department.GYNAECOLOGY],
    services: ['ডিজিটাল এক্স-রে', 'কালার ডপলার আল্ট্রাসনোগ্রাম', 'প্যাথলজি ও বায়োকেমিস্ট্রি', 'বিশেষজ্ঞ কনসালট্যান্ট চেম্বার'],
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'd4_center',
    name: 'Cumilla CT Scan MRI Specialized Diagnostic & Dialysis Center',
    facilityType: 'বিশেষায়িত ডায়াগনস্টিক ও ডায়ালাইসিস',
    categoryType: 'বেসরকারি',
    area: 'ঝাউতলা',
    address: 'Sel Fatima Jahanara Tower, Jhautola, Cumilla',
    phone: '01711-234567',
    bedCapacity: 'ডায়ালাইসিস ইউনিট',
    hasICU: false,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: true,
    hasCTScan: true,
    hasMRI: true,
    specialties: [Department.NEPHROLOGY, Department.NEUROLOGY],
    services: ['হাই-রেজোলিউশন সিটি স্ক্যান', 'এমআরআই', 'কিডনি ডায়ালাইসিস', 'ফার্টিলিটি কেয়ার'],
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  },
  {
    id: 'd5_center',
    name: 'Human Diagnostic Center & Hospital',
    facilityType: 'ডায়াগনস্টিক ও ক্লিনিক',
    categoryType: 'বেসরকারি',
    area: 'রেইসকোর্স',
    address: 'East side of Mukti Hospital, Racecourse Main Road, Cumilla',
    phone: '01712-889900',
    bedCapacity: '১০',
    hasICU: false,
    hasCCU: false,
    hasNICU: false,
    hasDialysis: false,
    hasCTScan: true,
    hasMRI: false,
    specialties: [Department.MEDICINE, Department.SURGERY],
    services: ['সিটি স্ক্যান', 'আল্ট্রাসাউন্ড', 'ডিজিটাল এক্স-রে', 'প্যাথলজি'],
    image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80',
    confidence: 'HIGH'
  }
];

export const DOCTORS: Doctor[] = [
  // CD Path & Hospital Doctors
  {
    id: 'cdp1',
    name: 'Prof. Dr. Md. Shahab Uddin',
    speciality: Department.MEDICINE,
    designation: 'সাবেক প্রফেসর ও বিভাগীয় প্রধান, মেডিসিন',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'Cumilla Medical College'],
    degree: 'MBBS, FCPS (Internal Medicine), FCPS (USA), FRCP (USA)',
    timing: 'সকাল ৯:০০ - দুপুর ৩:০০',
    phone: '01716-277211',
    fee: '১৫০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp2',
    name: 'Prof. Dr. Triptish Chandra Ghose',
    speciality: Department.CARDIOLOGY,
    designation: 'প্রিন্সিপাল ও অধ্যাপক (কার্ডিওলজি)',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'ময়নামতি মেডিকেল কলেজ (সাবেক)'],
    degree: 'MBBS, PhD (Cardiology), FACP, FESC, FRCP (Eden)',
    timing: 'দুপুর ১:০০ - রাত ৮:০০',
    phone: '01716-277211',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp3',
    name: 'Prof. Dr. Md. Helalur Rahman',
    speciality: Department.NEUROLOGY,
    designation: 'অধ্যাপক, নিউরোলজি ও মেডিসিন',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'Cumilla Medical College Hospital', 'Popular Diagnostic Center'],
    degree: 'MBBS, BCS (Health), FCPS (Medicine), MACP (USA)',
    timing: 'বিকাল ৩:৩০ - রাত ১০:০০',
    phone: '01716-277211',
    fee: '১২০০ টাকা',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp4',
    name: 'Prof. Dr. Jahangir Hossain Bhuiyan',
    speciality: Department.ONCOLOGY,
    designation: 'পরিচালক, অধ্যাপক ও বিভাগীয় প্রধান (অনকোলজি ও রেডিওথেরাপি)',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME],
    degree: 'MBBS, BCS, DMRT (Dhaka), TTRT (China)',
    timing: 'বিকাল ৫:০০ - রাত ৮:০০',
    phone: '01716-277211',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp5',
    name: 'Dr. Mohammad Shah Jamal',
    speciality: Department.GASTROENTEROLOGY,
    designation: 'অধ্যাপক, গ্যাস্ট্রোএন্টারোলজি',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'Cumilla Medical College Hospital'],
    degree: 'MBBS, BCS (Health), FCPS, MD (Gastroenterology)',
    timing: 'দুপুর ২:০০ - সন্ধ্যা ৬:০০',
    phone: '01716-277211',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp6',
    name: 'Dr. S M A Sufian',
    speciality: Department.PEDIATRICS,
    designation: 'সহযোগী অধ্যাপক ও বিভাগীয় প্রধান, শিশু বিভাগ',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'ইস্টার্ন মেডিকেল কলেজ'],
    degree: 'MBBS, DCH, MCPS, FCPS',
    timing: 'বিকাল ৩:০০ - সন্ধ্যা ৭:০০',
    phone: '01716-277211',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp7',
    name: 'Dr. Shima Mazumder',
    speciality: Department.GYNAECOLOGY,
    designation: 'কনসালট্যান্ট, গাইনি ও প্রসূতি',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME],
    degree: 'MBBS, BCS, FCPS (OBGYN)',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '01716-277211',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1594824813571-638f026361a6?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp8',
    name: 'Dr. Subrata Das Rupam',
    speciality: Department.ENT,
    designation: 'কনসালট্যান্ট, নাক কান গলা বিশেষজ্ঞ',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'ইবনে সিনা ডায়াগনস্টিক'],
    degree: 'MBBS, DLO (ENT)',
    timing: 'সকাল ১০:০০ - দুপুর ১:০০',
    phone: '01716-277211',
    fee: '৭০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp9',
    name: 'Dr. Mohammad Zahir Uddin',
    speciality: Department.NEPHROLOGY,
    designation: 'সহকারী অধ্যাপক, কিডনি রোগ বিশেষজ্ঞ',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'Cumilla Medical College Hospital'],
    degree: 'MBBS, BCS (Health), MD (Nephrology)',
    timing: 'দুপুর ২:০০ - বিকাল ৪:০০',
    phone: '01716-277211',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp10',
    name: 'Dr. Romana Sikder',
    speciality: Department.DERMATOLOGY,
    designation: 'সহকারী অধ্যাপক, যৌন ও চর্মরোগ',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME],
    degree: 'MBBS, DDV (BSMMU), MCPS (Dermatology)',
    timing: 'বিকাল ৩:০০ - সন্ধ্যা ৬:০০',
    phone: '01716-277211',
    fee: '৭০০ টাকা',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp11',
    name: 'Prof. Dr. Md. Harun Ar Rashid',
    speciality: Department.PSYCHIATRY,
    designation: 'সাবেক অধ্যাপক ও মানসিক রোগ বিশেষজ্ঞ',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME],
    degree: 'MBBS (DMC), BCS, MPhil (Psychiatry)',
    timing: 'সকাল ১০:০০ - দুপুর ২:০০',
    phone: '01716-277211',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'cdp12',
    name: 'Dr. Durlav Kanti Paul',
    speciality: Department.NEONATAL_PEDIATRICS_SURGEON,
    designation: 'শিশু সার্জন ও সহকারী অধ্যাপক',
    hospital: CD_PATH_NAME,
    multiFacilities: [CD_PATH_NAME, 'Cumilla Medical College'],
    degree: 'MBBS, BCS, MS (Pediatric Surgery)',
    timing: 'বিকাল ৫:০০ - রাত ৮:০০',
    phone: '01716-277211',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },

  // Cumilla Medical Center (Tower Hospital)
  {
    id: 'th1',
    name: 'Prof. Dr. Md. Azizul Haque',
    speciality: Department.MEDICINE,
    designation: 'সাবেক অধ্যাপক ও বিভাগীয় প্রধান, মেডিসিন',
    hospital: 'Cumilla Medical Center Pvt. Ltd. (Tower Hospital)',
    multiFacilities: ['Cumilla Medical Center Pvt. Ltd. (Tower Hospital)'],
    degree: 'MBBS, FCPS (Medicine), FRCP (Glasgow)',
    timing: 'সকাল ১০:০০ - দুপুর ২:০০',
    phone: '081-68921',
    fee: '১২০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'th2',
    name: 'Prof. Dr. A.H.M. Delwar Mamun',
    speciality: Department.ENT,
    designation: 'অধ্যাপক ও বিভাগীয় প্রধান, নাক কান গলা বিশেষজ্ঞ ও হেড নেক সার্জন',
    hospital: 'Cumilla Medical Center Pvt. Ltd. (Tower Hospital)',
    multiFacilities: ['Cumilla Medical Center Pvt. Ltd. (Tower Hospital)'],
    degree: 'MBBS, DLO, FCPS (ENT)',
    timing: 'বিকাল ৫:০০ - রাত ৮:০০',
    phone: '081-68921',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'th3',
    name: 'Dr. AKM Ziaul Huque',
    speciality: Department.VASCULAR_SURGERY,
    designation: 'ভাস্কুলার ও এন্ডোভাস্কুলার সার্জন',
    hospital: 'Cumilla Medical Center Pvt. Ltd. (Tower Hospital)',
    multiFacilities: ['Cumilla Medical Center Pvt. Ltd. (Tower Hospital)', 'NICVD, Dhaka'],
    degree: 'MBBS, MS (Cardiovascular & Thoracic Surgery)',
    timing: 'শুক্রবার ও শনিবার সকাল ১০:০০ - বিকাল ৪:০০',
    phone: '081-68921',
    fee: '১৫০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'th4',
    name: 'Dr. Md. Monirul Islam',
    speciality: Department.CHEST_MEDICINE,
    designation: 'সহকারী অধ্যাপক, বক্ষব্যাধি বিশেষজ্ঞ',
    hospital: 'Cumilla Medical Center Pvt. Ltd. (Tower Hospital)',
    multiFacilities: ['Cumilla Medical Center Pvt. Ltd. (Tower Hospital)'],
    degree: 'MBBS, DTCD, MD (Chest Diseases)',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '081-68921',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'th5',
    name: 'Prof. Dr. Shamsun Nahar',
    speciality: Department.GYNAECOLOGY,
    designation: 'অধ্যাপক, স্ত্রী ও প্রসূতি রোগ বিশেষজ্ঞ',
    hospital: 'Cumilla Medical Center Pvt. Ltd. (Tower Hospital)',
    multiFacilities: ['Cumilla Medical Center Pvt. Ltd. (Tower Hospital)'],
    degree: 'MBBS, FCPS (Obs & Gynae)',
    timing: 'সন্ধ্যা ৬:০০ - রাত ৯:০০',
    phone: '081-68921',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1594824813571-638f026361a6?auto=format&fit=crop&w=300&q=80'
  },

  // Popular Diagnostic Center
  {
    id: 'pop1',
    name: 'Prof. Dr. Md. Kamal Hossain Patwary',
    speciality: Department.MEDICINE,
    designation: 'অধ্যাপক ও বিভাগীয় প্রধান, মেডিসিন',
    hospital: 'Popular Diagnostic Center Ltd., Cumilla',
    multiFacilities: ['Popular Diagnostic Center Ltd., Cumilla', 'Cumilla Medical College Hospital'],
    degree: 'MBBS, FCPS (Internal Medicine), FACP (USA)',
    timing: 'বিকাল ৩:০০ - রাত ৮:০০',
    phone: '09666-787825',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'pop2',
    name: 'Associate Prof. Dr. Ganesh Chandra Saurav',
    speciality: Department.CARDIOLOGY,
    designation: 'চিফ কনসালট্যান্ট ও সহযোগী অধ্যাপক, হৃদরোগ বিভাগ',
    hospital: 'Popular Diagnostic Center Ltd., Cumilla',
    multiFacilities: ['Popular Diagnostic Center Ltd., Cumilla', 'Cumilla Medical College Hospital'],
    degree: 'MBBS, D-CARD, MD (Cardiology)',
    timing: 'বিকাল ৫:০০ - রাত ৯:০০',
    phone: '09666-787825',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'pop3',
    name: 'Assistant Prof. Dr. CM Kudrat-E-Khuda',
    speciality: Department.CARDIOLOGY,
    designation: 'সহকারী অধ্যাপক, ইন্টারভেনশনাল কার্ডিওলজি',
    hospital: 'Popular Diagnostic Center Ltd., Cumilla',
    multiFacilities: ['Popular Diagnostic Center Ltd., Cumilla', 'Cumilla Medical College'],
    degree: 'MBBS, BCS (Health), MD (Cardiology)',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '09666-787825',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'pop4',
    name: 'Assistant Prof. Dr. Shohag Chakrabarty',
    speciality: Department.PHYSICAL_MEDICINE,
    designation: 'সহকারী অধ্যাপক ও বিভাগীয় প্রধান, বাত ব্যথা ও প্যারালাইসিস বিশেষজ্ঞ',
    hospital: 'Popular Diagnostic Center Ltd., Cumilla',
    multiFacilities: ['Popular Diagnostic Center Ltd., Cumilla', 'General Hospital, Cumilla'],
    degree: 'MBBS, BCS, FCPS (Physical Medicine)',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '09666-787825',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'pop5',
    name: 'Assistant Prof. Dr. Md. Delwar Hossain',
    speciality: Department.HEPATOLOGY,
    designation: 'সহকারী অধ্যাপক, লিভার ও হেপাটোলজি বিশেষজ্ঞ',
    hospital: 'Popular Diagnostic Center Ltd., Cumilla',
    multiFacilities: ['Popular Diagnostic Center Ltd., Cumilla', 'Cumilla Medical College Hospital'],
    degree: 'MBBS, BCS (Health), MD (Hepatology)',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '09666-787825',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },

  // Moon Hospital
  {
    id: 'm1',
    name: 'Dr. Mahfuzur Rahman',
    speciality: Department.CARDIOLOGY,
    designation: 'কনসালট্যান্ট, কার্ডিওলজি',
    hospital: 'Moon Hospital Ltd.',
    multiFacilities: ['Moon Hospital Ltd.'],
    degree: 'MBBS, MD (Cardiology)',
    timing: 'বিকাল ৫:০০ - রাত ৯:০০',
    phone: '01766-556655',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'm2',
    name: 'Dr. Shamima Nasrin',
    speciality: Department.GYNAECOLOGY,
    designation: 'কনসালট্যান্ট, গাইনি ও প্রসূতি',
    hospital: 'Moon Hospital Ltd.',
    multiFacilities: ['Moon Hospital Ltd.'],
    degree: 'MBBS, FCPS (Obs & Gynae)',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '01766-556655',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1594824813571-638f026361a6?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'm3',
    name: 'Dr. Fahmidul Haque',
    speciality: Department.UROLOGY,
    designation: 'কনসালট্যান্ট, ইউরোলজি ও কিডনি সার্জারি',
    hospital: 'Moon Hospital Ltd.',
    multiFacilities: ['Moon Hospital Ltd.', 'Cumilla Medical College'],
    degree: 'MBBS, MS (Urology)',
    timing: 'বিকাল ৫:০০ - রাত ৮:০০',
    phone: '01766-556655',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=300&q=80'
  },

  // Cumilla Trauma Center
  {
    id: 'tr1',
    name: 'Dr. Zahirul Haque',
    speciality: Department.ORTHOPEDICS,
    designation: 'সিনিয়র কনসালট্যান্ট ও ট্রমা সার্জন',
    hospital: 'Cumilla Trauma Center',
    multiFacilities: ['Cumilla Trauma Center'],
    degree: 'MBBS, MS (Orthopedics), Fellow Trauma Surgery',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '01735-274020',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'tr2',
    name: 'Dr. S.M. Jahangir Kabir',
    speciality: Department.ENT,
    designation: 'কনসালট্যান্ট, নাক কান গলা বিশেষজ্ঞ',
    hospital: 'Cumilla Trauma Center',
    multiFacilities: ['Cumilla Trauma Center'],
    degree: 'MBBS, DLO (ENT)',
    timing: 'সন্ধ্যা ৬:০০ - রাত ৯:০০',
    phone: '01735-274020',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  },

  // General Hospital, Cumilla
  {
    id: 'gh1',
    name: 'Dr. Mohshina Abedin (Koli)',
    speciality: Department.GYNAECOLOGY,
    designation: 'সিনিয়র কনসালট্যান্ট, গাইনি ও প্রসূতি',
    hospital: 'General Hospital, Cumilla',
    multiFacilities: ['General Hospital, Cumilla'],
    degree: 'MBBS, BCS, FCPS (Obs & Gynae)',
    timing: 'সকাল ৯:০০ - দুপুর ২:০০',
    phone: '081-76930',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1594824813571-638f026361a6?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'gh2',
    name: 'Dr. Ashraful Matin Sagor',
    speciality: Department.ORTHOPEDICS,
    designation: 'কনসালট্যান্ট, অর্থোপেডিকস, ট্রমা ও স্পাইন',
    hospital: 'General Hospital, Cumilla',
    multiFacilities: ['General Hospital, Cumilla', 'Moon Hospital Ltd.'],
    degree: 'MBBS, BCS, D-ORTHO, MS (Orthopedics)',
    timing: 'বিকাল ৪:০০ - রাত ৮:০০',
    phone: '081-76930',
    fee: '৮০০ টাকা',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: 'gh3',
    name: 'Dr. Safiul Azam Chowdhury',
    speciality: Department.SURGERY,
    designation: 'প্রফেসর ও হেড, জেনারেল ও ল্যাপারোস্কোপিক সার্জারি',
    hospital: 'General Hospital, Cumilla',
    multiFacilities: ['General Hospital, Cumilla', 'Cumilla Medical College'],
    degree: 'MBBS, FCPS (Surgery)',
    timing: 'বিকাল ৫:০০ - রাত ৮:০০',
    phone: '081-76930',
    fee: '১০০০ টাকা',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80'
  }
];

export const AMBULANCES: Ambulance[] = [
  { id: 'a1', name: 'রেড ক্রিসেন্ট জরুরি অ্যাম্বুলেন্স সেবা', phone: '01711-555444', type: 'আইসিইউ', availability: '২৪/৭' },
  { id: 'a2', name: 'কুমিল্লা সেন্ট্রাল অ্যাম্বুলেন্স সার্ভিস', phone: '01819-607156', type: 'আইসিইউ', availability: '২৪/৭' },
  { id: 'a3', name: 'কুমিল্লা আল-আমিন অ্যাম্বুলেন্স সার্ভিস', phone: '01716-277211', type: 'স্ট্যান্ডার্ড', availability: '২৪/৭' },
  { id: 'a4', name: 'মেডিক্যাল কলেজ ইমার্জেন্সি অ্যাম্বুলেন্স', phone: '081-77563', type: 'আইসিইউ', availability: '২৪/৭' },
  { id: 'a5', name: 'শাসনগাছা দ্রুত অ্যাম্বুলেন্স ডিসপ্যাচ', phone: '01739-142170', type: 'বেসিক', availability: '২৪/৭' }
];

export const UPAZILA_DIRECTORY: UpazilaHealthData[] = [
  {
    upazila: 'আদর্শ সদর (সিটি ও সদর এলাকা)',
    governmentFacilities: '১টি (কুমিল্লা মেডিকেল কলেজ হাসপাতাল - ৫০০+ বেড)',
    privateFacilities: '৬০+ টি রেজিস্টার্ড হাসপাতাল ও ক্লিনিক',
    diagnosticCentres: '৩০+ টি আধুনিক ডায়াগনস্টিক সেন্টার',
    totalFacilities: '৯০+ টি প্রতিষ্ঠান',
    details: 'কান্দিরপাড়, ঝাউতলা, বাদুড়তলা ও টমসন ব্রিজ প্রধান স্বাস্থ্য হাব।'
  },
  {
    upazila: 'সদর দক্ষিণ',
    governmentFacilities: '১টি উপজেলা স্বাস্থ্য কমপ্লেক্স (৫০ শয্যা)',
    privateFacilities: '৫+ টি প্রাইভেট ক্লিনিক',
    diagnosticCentres: '৩+ টি প্যাথলজি ল্যাব',
    totalFacilities: '৯+ টি',
    details: 'পদুয়ার বাজার ও বেলতলী এলাকায় জরুরি ফার্স্ট এইড ও ক্লিনিক।'
  },
  {
    upazila: 'লাকসাম',
    governmentFacilities: '১টি উপজেলা স্বাস্থ্য কমপ্লেক্স ও ১টি ২০ শয্যা হাসপাতাল (মৈশাচাইল)',
    privateFacilities: '৮+ টি হাসপাতাল ও নার্সিং হোম',
    diagnosticCentres: '৩+ টি ডায়াগনস্টিক সেন্টার',
    totalFacilities: '১৩+ টি',
    details: 'লাকসাম জংশন ও বাজার এলাকায় বিশেষায়িত ডাক্তার চেম্বার ও ক্লিনিক।'
  },
  {
    upazila: 'দাউদকান্দি',
    governmentFacilities: '১টি ৫০ শয্যা হাসপাতাল ও ১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '১০+ টি ক্লিনিক',
    diagnosticCentres: '৫+ টি (৬০টি নিবন্ধিত কনসালট্যান্সি ও ডায়াগনস্টিক)',
    totalFacilities: '১৭+ টি',
    details: 'ঢাকা-চট্টগ্রাম হাইওয়ে সংলগ্ন আধুনিক জরুরি ট্রমা ও স্বাস্থ্যসেবা।'
  },
  {
    upazila: 'দেবীদ্বার',
    governmentFacilities: '১টি শিশু মাতৃ হাসপাতাল ও ১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৫+ টি প্রাইভেট হাসপাতাল',
    diagnosticCentres: '৩+ টি (৩০টি নিবন্ধিত কনসালট্যান্সি)',
    totalFacilities: '১০+ টি',
    details: 'উপজেলা সদরে শিশু ও মাতৃস্বাস্থ্য সেবা সম্বলিত প্রতিষ্ঠান।'
  },
  {
    upazila: 'বরুড়া',
    governmentFacilities: '১টি ২০ শয্যা হাসপাতাল ও ১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '১১টি বেসরকারি ক্লিনিক',
    diagnosticCentres: '২+ টি ডায়াগনস্টিক ল্যাব',
    totalFacilities: '১৫+ টি',
    details: 'বরুড়া বাজারে একাধিক প্রাইভেট হাসপাতাল ও সাধারণ ওটি সুবিধা।'
  },
  {
    upazila: 'ব্রাহ্মণপাড়া',
    governmentFacilities: '১টি ৫০ শয্যা উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৮টি বেসরকারি ক্লিনিক',
    diagnosticCentres: '২+ টি ডায়াগনস্টিক',
    totalFacilities: '১১+ টি',
    details: 'প্রাথমিক স্বাস্থ্যসেবা ও ডায়াগনস্টিক সেন্টার।'
  },
  {
    upazila: 'বুড়িচং',
    governmentFacilities: '১টি ৫০ শয্যা উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৪টি বেসরকারি ক্লিনিক',
    diagnosticCentres: '১+ টি ডায়াগনস্টিক',
    totalFacilities: '৬+ টি',
    details: 'জরুরি সেবা ও সাধারণ চিকিৎসকের চেম্বার।'
  },
  {
    upazila: 'চান্দিনা',
    governmentFacilities: '১টি ২০ শয্যা হাসপাতাল ও ১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৫+ টি বেসরকারি হাসপাতাল',
    diagnosticCentres: '২+ টি ডায়াগনস্টিক ল্যাব',
    totalFacilities: '৯+ টি',
    details: 'মহাসড়ক সংলগ্ন জরুরি চিকিৎসা ও ডায়াগনস্টিক সুবিধা।'
  },
  {
    upazila: 'চৌদ্দগ্রাম',
    governmentFacilities: '১টি ১০ শয্যা হাসপাতাল, ১টি ইউএইচসি ও ১টি বিশেষায়িত হাসপাতাল',
    privateFacilities: '৩+ টি ক্লিনিক',
    diagnosticCentres: '১+ টি ডায়াগনস্টিক',
    totalFacilities: '৭+ টি',
    details: 'চৌদ্দগ্রাম বাজারে জরুরি ওটি ও ম্যাটারনিটি ক্লিনিক।'
  },
  {
    upazila: 'হোমনা',
    governmentFacilities: '১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৩+ টি ক্লিনিক',
    diagnosticCentres: '২+ টি (১৩টি কনসালট্যান্সি নিবন্ধিত)',
    totalFacilities: '৬+ টি',
    details: 'উপজেলা স্বাস্থ্য কমপ্লেক্সে ইনডোর ও আউটডোর সেবা।'
  },
  {
    upazila: 'লালমাই',
    governmentFacilities: '১টি ২০ শয্যা হাসপাতাল',
    privateFacilities: '২+ টি ক্লিনিক',
    diagnosticCentres: '১+ টি ল্যাব',
    totalFacilities: '৪+ টি',
    details: 'বাগমারা ও লালমাই সংলগ্ন প্রাথমিক চিকিৎসা কেন্দ্র।'
  },
  {
    upazila: 'মেঘনা',
    governmentFacilities: '১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '২+ টি ক্লিনিক',
    diagnosticCentres: '১+ টি ল্যাব',
    totalFacilities: '৪+ টি',
    details: 'মেঘনা চরাঞ্চল ও সদরে সরকারি স্বাস্থ্যসেবা।'
  },
  {
    upazila: 'মনোহরগঞ্জ',
    governmentFacilities: '১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৩+ টি ক্লিনিক',
    diagnosticCentres: '১+ টি ল্যাব',
    totalFacilities: '৫+ টি',
    details: 'উপজেলা সদরে প্রাইভেট ক্লিনিক ও ল্যাবরেটরি।'
  },
  {
    upazila: 'মুরাদনগর',
    governmentFacilities: '১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৫+ টি ক্লিনিক',
    diagnosticCentres: '২+ টি ল্যাব',
    totalFacilities: '৮+ টি',
    details: 'মুরাদনগর ও কোম্পানীগঞ্জ বাজারে বেসরকারি ক্লিনিক।'
  },
  {
    upazila: 'নাঙ্গলকোট',
    governmentFacilities: '১টি ২০ শয্যা হাসপাতাল ও ১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৪+ টি ক্লিনিক',
    diagnosticCentres: '২+ টি ল্যাব',
    totalFacilities: '৮+ টি',
    details: 'নাঙ্গলকোট বাজারে সার্বক্ষণিক জরুরি চিকিৎসা।'
  },
  {
    upazila: 'তিতাস',
    governmentFacilities: '১টি উপজেলা স্বাস্থ্য কমপ্লেক্স',
    privateFacilities: '৪+ টি ক্লিনিক',
    diagnosticCentres: '২+ টি ল্যাব',
    totalFacilities: '৭+ টি',
    details: 'উপজেলা সদরে স্বাস্থ্য কমপ্লেক্স ও প্যাথলজি ল্যাব।'
  }
];

export const HEALTHCARE_CLUSTERS = [
  {
    name: 'কান্দিরপাড় ও লাকসাম রোড ক্লাস্টার',
    density: 'সর্বোচ্চ ঘনত্ব (১৫+ বড় প্রতিষ্ঠান)',
    description: 'কুমিল্লা শহরের কেন্দ্রস্থল। এখানে রয়েছে টাওয়ার হাসপাতাল, পপুলার ডায়াগনস্টিক, ল্যাবএইড, গোমতী হাসপাতাল, ট্রমা সেন্টার ও ন্যাশনাল ব্লাড ব্যাংক।',
    facilities: ['Cumilla Medical Center (Tower)', 'Popular Diagnostic', 'Gomati Hospital', 'Midland Hospital', 'Cumilla Trauma Center']
  },
  {
    name: 'ঝাউতলা ক্লাস্টার',
    density: 'উচ্চ ঘনত্ব',
    description: 'মুন হাসপাতাল, এইচআর হাসপাতাল, হেলথ অ্যান্ড ডক্টরস হাসপাতাল, মারিগোল্ড ও সিটি স্ক্যান সেন্টারের মূল কেন্দ্র।',
    facilities: ['Moon Hospital Ltd.', 'Health & Doctors Hospital', 'Cumilla Hospital & Diagnostic', 'Cumilla CT Scan MRI Center']
  },
  {
    name: 'রেইসকোর্স ও শাসনগাছা ক্লাস্টার',
    density: 'উচ্চ ঘনত্ব',
    description: 'জেনারেল হাসপাতাল, মুক্তি হাসপাতাল, মীম হাসপাতাল, নিউরন হসপিটাল ও হিউম্যান ডায়াগনস্টিক সেন্টারের অবস্থান।',
    facilities: ['General Hospital', 'Mukti Hospital', 'Neuron Hospital', 'Meem Hospital', 'Human Diagnostic']
  },
  {
    name: 'বাদুড়তলা ক্লাস্টার',
    density: 'বিশেষায়িত হাব',
    description: 'সিডি প্যাথ অ্যান্ড হসপিটালের অনকোলজি ও সুপার-স্পেশালিটি সেন্টার এবং কুমিল্লা সিটি হাসপাতাল।',
    facilities: ['CD Path & Hospital Pvt. Ltd.', 'Cumilla City Hospital', 'Mutatown Eye Hospital']
  },
  {
    name: 'টমসন ব্রিজ ও কোটবাড়ি রোড ক্লাস্টার',
    density: 'সরকারি ও বৃহৎ একাডেমি হাব',
    description: 'কুমিল্লা মেডিকেল কলেজ হাসপাতাল (৫০০+ বেড), ইবনে সিনা ডায়াগনস্টিক, সেন্ট্রাল হাসপাতাল ও ইউনাইটেড হাসপাতাল।',
    facilities: ['Cumilla Medical College Hospital', 'Ibn Sina Diagnostic', 'United Hospital', 'Cumilla Central Hospital']
  }
];
